// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIdCJnpGCnZwfGSppk-dHIjBNFXba9d0o',
    appId: '1:931847884577:web:6bfbfc0759bd4940983860',
    messagingSenderId: '931847884577',
    projectId: 'new1-quizapp-dee68',
    authDomain: 'new1-quizapp-dee68.firebaseapp.com',
    storageBucket: 'new1-quizapp-dee68.appspot.com',
    measurementId: 'G-4EBHYE868G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxbyz8lpXGIPiHCohY7aqMX24xnr8TcTk',
    appId: '1:931847884577:android:12a806da745bedac983860',
    messagingSenderId: '931847884577',
    projectId: 'new1-quizapp-dee68',
    storageBucket: 'new1-quizapp-dee68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNqsV-dwS7qulTbFetLOCVSVTkd5dGWEI',
    appId: '1:931847884577:ios:d834f305d02c5d2c983860',
    messagingSenderId: '931847884577',
    projectId: 'new1-quizapp-dee68',
    storageBucket: 'new1-quizapp-dee68.appspot.com',
    iosBundleId: 'com.extrawest.quizapp',
  );
}
