// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT4MqjSlxTn0Fhw0Xk48Y1MpSfHvZWSvg',
    appId: '1:478690371739:web:e2ff63b67fcee031287e3e',
    messagingSenderId: '478690371739',
    projectId: 'quizapp-69a6b',
    authDomain: 'quizapp-69a6b.firebaseapp.com',
    storageBucket: 'quizapp-69a6b.appspot.com',
    measurementId: 'G-PSPHZK6VY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfY1V1_D3l-4mdqiZp6W_TujE6o1QUQ3E',
    appId: '1:478690371739:android:fb037856097a3669287e3e',
    messagingSenderId: '478690371739',
    projectId: 'quizapp-69a6b',
    storageBucket: 'quizapp-69a6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi3tn98Yg__ci4nfIzBQRRumXy5EF3VuE',
    appId: '1:478690371739:ios:940ac4e55d893148287e3e',
    messagingSenderId: '478690371739',
    projectId: 'quizapp-69a6b',
    storageBucket: 'quizapp-69a6b.appspot.com',
    androidClientId: '478690371739-0o6hikoje0buf4ll0i573ancphuuuj52.apps.googleusercontent.com',
    iosClientId: '478690371739-g50340coi8ql4foqblkp9jl4gmbb44sc.apps.googleusercontent.com',
    iosBundleId: 'com.extrawest.quizapp',
  );
}
